name: Attendance verification
on:
  workflow_dispatch:
    inputs:
      sheetid:
        description: 'Google Sheet ID'     
        required: true
      eventid:
        description: 'Event ID'
        required: true
      tolerance:
        description: 'Tolerance Gap'
        required: true
        default: '8'
jobs:
  Attendance-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: gpg --batch -d --passphrase ${{ secrets.SERVICE_SECRET }} service_creds.json.gpg > service_creds.json
      - run: npx ts-node index.ts ${{ github.event.inputs.sheetid }} ${{ github.event.inputs.eventid }} ${{ github.event.inputs.tolerance }}
      